SCREEN_WIDTH = 1920
SCREEN_HEIGHT = 1080
SCREEN_NAME = "Scarlet Game Jam 2022 Fall"

FONT_PATH_REGULAR = "fonts/SpaceMono-Regular.ttf"

BACKGROUND_ROWS_NUM = SCREEN_WIDTH / 20
BACKGROUND_COLS_NUM = SCREEN_HEIGHT / 20

MAP_RADIUS = 500
NODE_DRAW_RADIUS = 25

NODE_HOUSE = 0
NODE_DELIVERY_HQ = 1

INIT_BALANCE = 5000
INIT_NODES = 18
INIT_CONNECTIONS_PER_NODE = 2
INIT_CONNS_FROM_HQ = 2
INIT_DELIVERY_TRUCKS = 3

TIME_TO_REACH_ENDGOAL = 60 * 5
MONEY_GOAL = 15000
INIT_GAS_GAL_PER_MILE_PRICE = 3
MAX_GAS_PRICE = 4.5

PACKAGE_COST_RANGE = [100, 100]
SECONDS_PER_PACKAGE = 8
BUMPY_CONN_PROB = 0.7
FAST_SHIPPING_PROB = 0.4
FAST_SHIPPING_RANGE = [80, 120]
SPEED_MODIFIER = 1.5
CONN_DIST = [30, 70]
BUMPY_CONN_DIST = [20, 50]
HEALTH_DEC_SPEED = 4
CLICK_HEAL = 4.5
HEAL_COST = 0.05
